# see also: https://packaging.python.org/guides/supporting-windows-using-appveyor/

# select image with MinGW-w64 available
image: Visual Studio 2015

environment:

  matrix:
    - PYTHONPATH: C:\Python37-x64
    # TODO add more Python versions,
    # see https://www.appveyor.com/docs/build-environment/#python

  global:
    PATH:  C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;C:\msys64\usr\bin;$(PATH)
    CXX:   g++
    CC:    gcc
    GCOV:  gcov
    MAKE:  mingw32-make
    CMAKE: cmake -G "MSYS Makefiles"

install:
  - 'set PATH=%PYTHONPATH%;%PYTHONPATH%\Scripts;%PATH%'
  - 'python --version'
  - '%CXX% --version'
  - 'python -m pip install --upgrade pip pytest coverage codecov'
  - '%MAKE% setup-dev PYTHON=python'

build: off

test_script:
  - '%MAKE% test PYTHON=python TEST_OPTS="--cov=gcovr --cov-branch"'
  - 'codecov -X gcov search'


notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/5c98eaf2d3e76753369e
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
