# see also: https://packaging.python.org/guides/supporting-windows-using-appveyor/

# select image with MinGW-w64 available
image: Visual Studio 2015

environment:

  matrix:
    - PYTHONPATH: C:\Python27
    - PYTHONPATH: C:\Python36-x64
    # TODO add more Python versions,
    # see https://www.appveyor.com/docs/build-environment/#python

  global:
    PATH:  C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin;C:\msys64\usr\bin;$(PATH)
    CXX:   g++
    CC:    gcc
    GCOV:  gcov
    MAKE:  mingw32-make
    CMAKE: cmake -G "MSYS Makefiles"

install:
  # verify compiler version
  - 'set PATH=%PYTHONPATH%;%PYTHONPATH%\Scripts;%PATH%'
  - 'python -V'
  - '%CXX% --version'
  - 'python -m pip install pytest pytest-cov'
  - 'python -m pip install ply'
  - 'python -m pip install ordereddict'
  - 'python -m pip install pyutilib'
  - 'python -m pip install coverage'
  - 'python -m pip install codecov'
  - 'python setup.py develop'

build: off

test_script:
  - 'python -m pytest -v --cov=gcovr --cov-branch gcovr'
  - 'codecov -X gcov search'
